name: FakeChieve
main: io.github.ratismal.fakechieve.FakeChieve
version: 1.0.4
depend:
commands:
  fakechieve:
      description: Base FC command
      usage: /fakechieve <player> <message1> <message2> 
      permission: 
      permission-message: Bugger off, you don't have the rights to do that!